x<-read_csv(file = 'hw1_data.csv',col_names = T)
colnames(x)
x[1:2,]
x[nrow(x)]
x[152:153]
x[152:153,]
x$Ozone[47]
na<-is.na(x$Ozone)
sum(na)
nona<-na.omit(x$Ozone,,drop(FALSE))
mean(nona)
help("na.omit")
nona<-na.omit(x)
mean(nona$Ozone)
oz<-x[x$Ozone>31,,drop(FALSE)]
oz1<-x[x$Temp>90,,drop(false)]
oz1<-x[x$Temp>90,,drop(FALSE)]
mean(oz1$Solar.R)
oz1<-oz[oz$Temp>90,,drop(FALSE)]
mean(oz1$Solar.R)
oz2<-na.omit(oz1)
mean(oz2)
mean(oz2$Solar.R)
t<-x[x$Month==6,,drop(FALSE)]
mean(t$Temp)
t<-x[x$Month==5,,drop(FALSE)]
mean(t$Temp)
max(t$Ozone)
t1<-na.omit(t)
max(t1)
t<-x[x$Month==5,,drop(FALSE)]
t1<-na.omit(t)
max(t1$Ozone)
